# Generated by Django 5.2.4 on 2025-07-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Slug',
            field=models.SlugField(auto_created=True, max_length=255, null=True, unique=True),
        ),
    ]
