# Generated by Django 5.2.1 on 2025-07-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_menu_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Table',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
